create release workflow
Contrast-Security-OSS/node-route-metrics pull request #23
Opened 2024-03-07 12:10 UTC by bmacnaughton

release on push of a version-format tag

2024-12-06 18:13 UTC, tough-griff requested changes

2024-12-06 18:13 UTC, tough-griff commented on .github/workflows/release.yml
> +    tags: ['v[0-9]+.[0-9]+.[0-9]+*']
It looks like all of our other repos have moved to releasing on `workflow_dispatch`. I know we used the tag method in the past, but should we just allow this to release on a dispatch as well for consistency?

If we do so I think we could remove the test portion below since we'll only dispatch workflows from main.

2024-12-06 18:13 UTC, tough-griff commented on .github/workflows/release.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v4
```

we'll need to move this to a specific hash sometime soon, but for the time being we should use the newest versions since old ones on old node versions will soon be deprecated.

2024-12-06 18:13 UTC, tough-griff commented on .github/workflows/release.yml
> +        uses: actions/setup-node@v3
```suggestion
        uses: actions/setup-node@v4
```

2024-12-09 15:22 UTC, bmacnaughton commented on .github/workflows/release.yml
> +    tags: ['v[0-9]+.[0-9]+.[0-9]+*']
completely agree. i think the workflow_dispatch approach makes more sense than this. i just wasn't familiar with it when i did this, and i never went back.

thanks.

2024-12-09 15:40 UTC, bmacnaughton commented on .github/workflows/release.yml
> +        run: pip install setuptools
to prove that i make copy/pasta errors?

2024-12-09 19:17 UTC, tough-griff approved these changes
Approved with one caveat.

2024-12-09 19:20 UTC, tough-griff approved these changes
Approved with one caveat.

2024-12-09 19:20 UTC, tough-griff commented on .github/workflows/release.yml
> +      run: npm test
I don't think we need to test first if we're running on dispatches against main, what do you think?

We should be in a passing state since you can only merge on passing tests, but I suppose there's a nonzero chance something happens.

I'll leave it up to you, but if we keep it:
```suggestion
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
    name: Test on ${{ matrix.os }} with node v${{ matrix.node-version }}
    steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
```

2024-12-10 04:59 UTC, bmacnaughton commented on .github/workflows/release.yml
> +      run: npm test
once again, a good suggestion - thanks. i don't think we need to test again. i will remove the redundant tests.

2024-12-10 13:13 UTC, merged